name: Tim Rose
title: Tim Rose | Software Engineer
description: I'm passionate about designing and developing tools to make everyday life a bit more fun
url: https://timrose.me
baseurl: ""
favicon: https://timrose.me/img/icon.png
gtag: UA-111565159-1
cover: https://timrose.me/img/cover.png
keywords: software, developer, design, tim, rose, flowor, umassd, umass, dartmouth, intern

fonturl: https://fonts.googleapis.com/css?family=Inconsolata:400,700
