# Details
title: Tim Rose
description: Software Developer
url: 'http://timrose.me'
baseurl:

# Fonts
font-url: 'https://fonts.googleapis.com/css?family=Roboto'

# Google Analytics
# tracking-id: UA-89387804-1
